services:
  - type: web
    name: eyebot-chatbot
    env: python
    buildCommand: python install_dependencies.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0